name: Check Spelling
on:
  pull_request:
    paths:
      - '**.txt'
      - '**.md'
jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check Spelling
        uses: UnicornGlobal/spellcheck-github-actions@master
