name: Test and Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches: [master]

jobs:
  test:
    name: Test and Build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Get Yarn Cache Directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Installing project dependencies
        run: yarn install
      - name: Get latest COVID-19 data
        run: yarn covid:get
      - name: Run Tests
        run: yarn test:unit
      - name: Build
        run: yarn build
        env:
          VUE_APP_SUBSCRIPTION_FORM_URL: ${{ secrets.VUE_APP_SUBSCRIPTION_FORM_URL }}
          VUE_APP_GTM_ID: ${{ secrets.VUE_APP_GTM_ID }}
      - uses: jakejarvis/s3-sync-action@master
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist'

  lint:
    name: Lint Code Base
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_YAML: true
          VALIDATE_MD: true
